name: Update README.md

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 */1 * *"

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install bs4
        pip install requests
        pip install pytz
    - name: Update README.md
      run: |
        python main.py
    - name: Commit README.md
      run: |
        git pull
        git add .
        git diff
        git config --local user.email "th885172@gmail.com"
        git config --local user.name "Cherrue"
        git commit -m "[Auto Update] Update recent blog posts to README.md"
        git push
